version: '3.9'
services:
  api:
    container_name: app-api
    build:
      context: ./api
    ports:
      - '4000:4000'
  client:
    container_name: app-client
    build:
      context: ./client
    ports:
      - '3000:3000'
    stdin_open: true
  proxy:
    container_name: app-proxy
    build:
      context: ./proxy
    ports:
      - '8080:80'
